name: Build and Publish Docker Images

on:
  push:
    branches: [ main, aspire ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_BFF: ${{ github.repository }}/bff
  IMAGE_NAME_WEBAPI: ${{ github.repository }}/webapi

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate version tag
      id: version
      run: |
        DATE=$(date +%Y-%m-%d)
        BRANCH=${GITHUB_REF_NAME}
        BUILD_NUMBER=${GITHUB_RUN_NUMBER}
        echo "version=${DATE}.${BRANCH}.${BUILD_NUMBER}" >> $GITHUB_OUTPUT

    - name: Extract metadata for BFF
      id: meta-bff
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BFF }}
        tags: |
          type=raw,value=${{ steps.version.outputs.version }}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Extract metadata for WebAPI
      id: meta-webapi
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_WEBAPI }}
        tags: |
          type=raw,value=${{ steps.version.outputs.version }}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push BFF image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./src/BFF/Dockerfile
        push: true
        tags: ${{ steps.meta-bff.outputs.tags }}
        labels: ${{ steps.meta-bff.outputs.labels }}

    - name: Build and push WebAPI image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./src/WebAPI/Dockerfile
        push: true
        tags: ${{ steps.meta-webapi.outputs.tags }}
        labels: ${{ steps.meta-webapi.outputs.labels }}