name: Release

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v2025-01-21, v1.0.0, etc.

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_BFF: ${{ github.repository }}/bff
  IMAGE_NAME_WEBAPI: ${{ github.repository }}/webapi

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/Directory.Packages.props', '**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Aspire CLI
        run: dotnet tool install -g aspire.cli --prerelease

      - name: Generate docker-compose with Aspire CLI
        run: |
          cd src/Aspire/AppHost
          
          # Generate docker-compose and .env files using Aspire CLI
          # This creates the full stack configuration with vendor services
          aspire publish --output-path ../../../deployment-output
            
          # Copy generated files 
          cd ../../../
          cp deployment-output/docker-compose.yaml docker-compose.prod.yml
          cp deployment-output/.env .env.generated
          
          # Replace environment variable placeholders with actual registry images in the env file
          sed -i "s|WEBAPI_IMAGE=webapi:latest|WEBAPI_IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME_WEBAPI }}:${{ github.ref_name }}|g" .env.generated
          sed -i "s|BFF_IMAGE=bff:latest|BFF_IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BFF }}:${{ github.ref_name }}|g" .env.generated
          
          # Update the volumes path in docker-compose for production deployment  
          sed -i 's|/Users/.*/src/Aspire/AppHost/Realms|./keycloak/realms|g' docker-compose.prod.yml
          
          # Add production optimizations
          # Update expose to ports for external access
          sed -i 's|expose:|ports:|g' docker-compose.prod.yml
          
          # Add restart policies for production
          sed -i '/networks:/i\    restart: "unless-stopped"' docker-compose.prod.yml

      - name: Generate Dockerfiles and build images
        run: |
          # Generate Dockerfile for WebAPI using .NET SDK
          cat > src/WebAPI/Dockerfile << 'EOF'
          FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
          USER $APP_UID
          WORKDIR /app
          EXPOSE 8080
          EXPOSE 8081
          
          FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
          ARG BUILD_CONFIGURATION=Release
          WORKDIR /src
          COPY ["src/WebAPI/HeadStart.WebAPI.csproj", "src/WebAPI/"]
          COPY ["src/Aspire/ServiceDefaults/HeadStart.Aspire.ServiceDefaults.csproj", "src/Aspire/ServiceDefaults/"]
          COPY ["src/SharedKernel/HeadStart.SharedKernel.csproj", "src/SharedKernel/"]
          COPY ["src/SharedKernel.Models/HeadStart.SharedKernel.Models.csproj", "src/SharedKernel.Models/"]
          COPY ["Directory.Build.props", "."]
          COPY ["Directory.Packages.props", "."]
          RUN dotnet restore "src/WebAPI/HeadStart.WebAPI.csproj"
          COPY . .
          WORKDIR "/src/src/WebAPI"
          RUN dotnet build "HeadStart.WebAPI.csproj" -c $BUILD_CONFIGURATION -o /app/build
          
          FROM build AS publish
          ARG BUILD_CONFIGURATION=Release
          RUN dotnet publish "HeadStart.WebAPI.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false /p:SkipClientGeneration=true
          
          FROM base AS final
          WORKDIR /app
          COPY --from=publish /app/publish .
          ENTRYPOINT ["dotnet", "HeadStart.WebAPI.dll"]
          EOF
          
          # Generate Dockerfile for BFF using .NET SDK  
          cat > src/BFF/Dockerfile << 'EOF'
          FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
          USER $APP_UID
          WORKDIR /app
          EXPOSE 8080
          EXPOSE 8081
          
          FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
          ARG BUILD_CONFIGURATION=Release
          WORKDIR /src
          COPY ["src/BFF/HeadStart.BFF.csproj", "src/BFF/"]
          COPY ["src/Aspire/ServiceDefaults/HeadStart.Aspire.ServiceDefaults.csproj", "src/Aspire/ServiceDefaults/"]
          COPY ["src/Client/HeadStart.Client.csproj", "src/Client/"]
          COPY ["src/SharedKernel/HeadStart.SharedKernel.csproj", "src/SharedKernel/"]
          COPY ["src/SharedKernel.Models/HeadStart.SharedKernel.Models.csproj", "src/SharedKernel.Models/"]
          COPY ["Directory.Build.props", "."]
          COPY ["Directory.Packages.props", "."]
          RUN dotnet restore "src/BFF/HeadStart.BFF.csproj"
          COPY . .
          WORKDIR "/src/src/BFF"
          RUN dotnet build "HeadStart.BFF.csproj" -c $BUILD_CONFIGURATION -o /app/build
          
          FROM build AS publish
          ARG BUILD_CONFIGURATION=Release
          RUN dotnet publish "HeadStart.BFF.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false
          
          FROM base AS final
          WORKDIR /app
          COPY --from=publish /app/publish .
          ENTRYPOINT ["dotnet", "HeadStart.BFF.dll"]
          EOF

      - name: Build and push WebAPI image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/WebAPI/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_WEBAPI }}:${{ github.ref_name }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME_WEBAPI }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push BFF image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/BFF/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BFF }}:${{ github.ref_name }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BFF }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create production .env template
        run: |
          cat > .env.production << EOF
          # Production Environment Configuration
          # Copy this file to .env and fill in the values
          
          # Database Configuration
          POSTGRES_PASSWORD=your_secure_postgres_password_here
          
          # Keycloak Configuration  
          KEYCLOAK_PASSWORD=your_secure_keycloak_admin_password_here
          
          # Generated for tag: ${GITHUB_REF_NAME}
          # Images used:
          # - BFF: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BFF }}:${GITHUB_REF_NAME}
          # - WebAPI: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_WEBAPI }}:${GITHUB_REF_NAME}
          EOF

      - name: Create deployment package
        run: |
          mkdir -p deployment-package
          cp docker-compose.prod.yml deployment-package/docker-compose.yml
          cp .env.production deployment-package/.env.template
          cp .env.generated deployment-package/.env.example
          
          # Copy Keycloak realm configuration if it exists
          if [ -d "src/Aspire/AppHost/Realms" ]; then
            mkdir -p deployment-package/keycloak
            cp -r src/Aspire/AppHost/Realms deployment-package/keycloak/realms
          fi
          
          # Create deployment instructions
          cat > deployment-package/README.md << EOF
          # Deployment Package for ${GITHUB_REF_NAME}
          
          This package contains everything needed to deploy your application using Docker Compose.
          
          ## Quick Start
          
          1. Copy \`.env.template\` to \`.env\` and configure your passwords
          2. Run: \`docker-compose up -d\`
          3. Access your application at http://localhost:5000
          
          ## Services
          
          - **Application (BFF)**: http://localhost:5000
          - **API**: http://localhost:5001  
          - **Keycloak Admin**: http://localhost:8080 (admin/[KEYCLOAK_PASSWORD])
          - **Mailpit**: http://localhost:8025
          - **Aspire Dashboard**: http://localhost:18888
          - **PostgreSQL**: localhost:5432
          
          ## Images Used
          
          - BFF: \`${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BFF }}:${GITHUB_REF_NAME}\`
          - WebAPI: \`${{ env.REGISTRY }}/${{ env.IMAGE_NAME_WEBAPI }}:${GITHUB_REF_NAME}\`
          
          ## Prerequisites
          
          - Docker and Docker Compose installed
          - Configured \`.env\` file with secure passwords
          
          ## Commands
          
          \`\`\`bash
          # Start all services
          docker-compose up -d
          
          # View logs
          docker-compose logs -f
          
          # Stop all services
          docker-compose down
          
          # Stop and remove volumes (CAUTION: This will delete all data)
          docker-compose down -v
          \`\`\`
          EOF
          
          # Create a zip file of the deployment package
          cd deployment-package
          zip -r "../deployment-${GITHUB_REF_NAME}.zip" .
          cd ..

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            deployment-${{ github.ref_name }}.zip
            deployment-package/docker-compose.yml
            deployment-package/.env.template
            deployment-package/.env.example
          body: |
            ## Release ${{ github.ref_name }}
            
            This release includes:
            
            ### Docker Images Published
            - **BFF**: `${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BFF }}:${{ github.ref_name }}`
            - **WebAPI**: `${{ env.REGISTRY }}/${{ env.IMAGE_NAME_WEBAPI }}:${{ github.ref_name }}`
            
            ### Deployment Package
            Download `deployment-${{ github.ref_name }}.zip` for a complete deployment package including:
            - Production-ready `docker-compose.yml`
            - Environment template (`.env.template`)
            - Deployment instructions
            - Keycloak realm configuration
            
            ### Quick Deploy
            ```bash
            # Download and extract the deployment package
            wget https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/deployment-${{ github.ref_name }}.zip
            unzip deployment-${{ github.ref_name }}.zip
            cd deployment-package
            
            # Configure environment
            cp .env.template .env
            # Edit .env with your secure passwords
            
            # Deploy
            docker-compose up -d
            ```
            
            ### Access Points
            - **Application**: http://localhost:5000
            - **API**: http://localhost:5001
            - **Keycloak**: http://localhost:8080
            - **Mailpit**: http://localhost:8025
            - **Aspire Dashboard**: http://localhost:18888
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}